version: "3.1"

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethink
    volumes:
      - ./db/data:/data
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"

  nodefrontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
    container_name: nodefrontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/opt/app
      - notusedfront:/opt/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=3001
      - PORT=3000

  nodebackend:
    build:
      context: ./backend
      args:
        - NODE_ENV=development
    container_name: nodebackend
    # either use legacy debug config or new inspect (dont really understand this yet?)
    # NOTE: if nodemon isn't restarting on changes, there can somtimes be problems with windows not seeing file changes.
    # se https://github.com/remy/nodemon#application-isnt-restarting for more information
    # command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --debug=0.0.0.0:9229
    ports:
      - "3001:3001"
      - "5858:5858"
      - "9229:9229"
    volumes:
      - ./backend:/opt/app
      # this is to prevent host node_modules from accidently getting mounted in the container.
      # in case you want to use node or npm both outside container and also inside the container for test/lint etc
      # so this will overwrite the default node_modules dir in container so it won't conflict with our /opt/node_modules location
      - notusedback:/opt/app/node_modules
    environment:
      - NODE_ENV=development
      - SOCKETIO_SERVER_PORT=3001
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=28015
    links:
      - rethinkdb
    depends_on:
      - rethinkdb
          
volumes:
  notusedfront:
  notusedback:
